import Auth from './AuthApi'
import Question from './QuestionApi'
import Question2 from './Question2Api'
import Promotion from './PromotionApi'
import Trade from './TradeApi'
import Face from './FaceApi'
import Version from './VersionApi'
import Showroom from './ShowroomApi'
import Webboard from './WebboardApi'
import Market from './MarketApi'
export default { Auth, Question, Promotion, Trade, Face, Version, Question2, Showroom, Webboard, Market }
