# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CheckPhra' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheckPhra
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'FBSDKLoginKit'

  #target 'CheckPhra-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  # pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'RCTImage',
      'RCTWebSocket',
      'RCTNetwork',
      'DevSupport'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'GoogleAppMeasurement', '~> 5.2.0'
  
  pod 'RNIap', :path => '../node_modules/react-native-iap'

  target 'CheckPhraTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
      end
  end

end

target 'CheckPhra-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheckPhra-tvOS

  target 'CheckPhra-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
