# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CheckPhra' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheckPhra
  pod 'Firebase/Core', '~> 5.9.0'

  #target 'CheckPhra-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  target 'CheckPhraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CheckPhra-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheckPhra-tvOS

  target 'CheckPhra-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
