# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CheckPhra' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheckPhra
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'Firebase/AdMob', '~> 6.2.0'
  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'
  pod 'FBSDKLoginKit'

  pod 'GoogleUtilities', '6.2.0'
  pod 'GoogleAppMeasurement', '6.0.1'
  #target 'CheckPhra-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'RCTImage',
      'RCTWebSocket',
      'RCTNetwork',
      'DevSupport'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
#  pod 'GoogleAppMeasurement', '~> 5.2.0'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'CheckPhraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
      end
  end

end

target 'CheckPhra-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheckPhra-tvOS

  target 'CheckPhra-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
